#%RAML 1.0
title: Flights Process API
version: v1

types:
  Flight: !include datatypes/Flight.raml

/flights:
  get:
    queryParameters:
      destination?:
        type: string
        enum: ["SFO", "LAX", "CLE"]
        displayName: Flight Destination
        description: IATA code of the airport where the flight is scheduled to arrive.
        example: "LAX"

    responses:
      200:
        body:
          application/json:
            type: Flight[]
            example: !include examples/flights-example.json

  /{flightId}:
    get:
      responses:
        200:
          body:
            application/json:
              type: Flight
              example: !include examples/flight-example.json