#%RAML 1.0
title: Flights System API
version: v1
baseUri: /american-flights-sa/api/v1
mediaType: application/json

types:
  Flight: !include datatypes/Flight.raml

/flights:
  get:
    queryParameters:
      destination?:
        type: string
    responses:
      200:
        body:
          application/json:
            type: Flight[]
            example: !include examples/flights-example.json

  /{flightId}:
    get:
      responses:
        200:
          body:
            type: Flight
            example: !include examples/flight-example.json
